apiVersion: v1
kind: Service
metadata:
  name: svc-kakaroto
  labels:
    app: kakaroto
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30890
    targetPort: 8080
  selector:
    app: kakaroto

