apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-me
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/me"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-me
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
